'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class WebUserControl1

  '''<summary>
  '''MainPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MainPanel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ToolStripPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ToolStripPanel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ToolStripTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ToolStripTable As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''TableRow1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableCell1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''PageLabel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PageLabel As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TableCell2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''PreviousPageButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PreviousPageButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell3 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''NextPageButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents NextPageButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell4 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''GoToLabel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents GoToLabel As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''TableCell5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell5 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''PageNumberTextBox control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PageNumberTextBox As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TableCell6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell6 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''ZoomOutButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ZoomOutButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell7 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''ZoomInButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ZoomInButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell8 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''RotateCCButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RotateCCButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell9 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell9 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''RotateCButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RotateCButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell10 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell10 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''FitToScreenButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FitToScreenButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell11 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell11 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''FitToWidthButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FitToWidthButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell12 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell12 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''ActualSizeButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ActualSizeButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell13 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell13 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''SearchButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell14 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell14 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''SearchTextBox control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SearchTextBox As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TableCell15 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell15 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''SearchPreviousButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SearchPreviousButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableCell16 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell16 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''SearchNextButton control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SearchNextButton As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''PicPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PicPanel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''Table1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''BookmarkCell control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookmarkCell As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''BookmarkPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookmarkPanel As Global.CustomControls.StatefullScrollPanel

  '''<summary>
  '''BookmarkTable control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookmarkTable As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''BookmarkRow control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookmarkRow As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''BookmarkContentCell control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BookmarkContentCell As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''PicCell control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PicCell As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''ImagePanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ImagePanel As Global.CustomControls.StatefullScrollPanel

  '''<summary>
  '''CurrentPageImage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CurrentPageImage As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''HiddenPageNumber control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenPageNumber As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''HiddenBrowserWidth control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenBrowserWidth As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''HiddenBrowserHeight control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenBrowserHeight As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''HiddenPageNav control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HiddenPageNav As Global.System.Web.UI.WebControls.Button
End Class
